const doctors = [
  {
    id: 1,
    name: "Dr. Ayesha Malik",
    specialty: "Gynecologist",
    qualification: "MBBS, FCPS (Obs & Gynae)",
    experience: 14,
    fee: 2500,
    rating: 4.9,
    reviews: 312,
    area: "F-8 Markaz",
    clinic: "Shifa International Hospital",
    address: "Shifa International Hospital, H-8/4, Islamabad",
    phone: "051-8460911",
    available: true,
    nextSlot: "Today 4:00 PM",
    timings: "Mon–Sat: 4:00 PM – 8:00 PM",
    about: "Specialist in high-risk pregnancies, infertility, and laparoscopic surgery with 14 years of clinical experience.",
    tags: ["Pregnancy", "Infertility", "PCOS", "Laparoscopy"],
    gender: "Female",
    photo: "https://ui-avatars.com/api/?name=Ayesha+Malik&background=0ea5e9&color=fff&size=128"
  },
  {
    id: 2,
    name: "Dr. Tariq Mehmood",
    specialty: "Cardiologist",
    qualification: "MBBS, FRCP (London), FACC",
    experience: 22,
    fee: 4000,
    rating: 4.8,
    reviews: 245,
    area: "Blue Area",
    clinic: "PIMS Hospital",
    address: "Pakistan Institute of Medical Sciences, G-8/3, Islamabad",
    phone: "051-9261170",
    available: true,
    nextSlot: "Tomorrow 10:00 AM",
    timings: "Mon–Fri: 10:00 AM – 2:00 PM",
    about: "Interventional cardiologist with expertise in angioplasty, stenting, and heart failure management.",
    tags: ["Heart Disease", "Angioplasty", "ECG", "Hypertension"],
    gender: "Male",
    photo: "https://ui-avatars.com/api/?name=Tariq+Mehmood&background=0f766e&color=fff&size=128"
  },
  {
    id: 3,
    name: "Dr. Sana Riaz",
    specialty: "Dermatologist",
    qualification: "MBBS, MCPS (Dermatology)",
    experience: 9,
    fee: 2000,
    rating: 4.7,
    reviews: 198,
    area: "G-10 Markaz",
    clinic: "Skin Care Clinic",
    address: "G-10 Markaz, Islamabad",
    phone: "051-2296001",
    available: true,
    nextSlot: "Today 6:00 PM",
    timings: "Mon–Sat: 12:00 PM – 9:00 PM",
    about: "Expert in acne treatment, laser therapy, hair loss, and cosmetic dermatology procedures.",
    tags: ["Acne", "Laser Hair Removal", "Skin Whitening", "Hair Loss"],
    gender: "Female",
    photo: "https://ui-avatars.com/api/?name=Sana+Riaz&background=7c3aed&color=fff&size=128"
  },
  {
    id: 4,
    name: "Dr. Hassan Qureshi",
    specialty: "Orthopedic Surgeon",
    qualification: "MBBS, FCPS (Orthopedics)",
    experience: 17,
    fee: 3500,
    rating: 4.9,
    reviews: 421,
    area: "DHA Phase 2",
    clinic: "Maroof International Hospital",
    address: "Maroof International Hospital, F-10/2, Islamabad",
    phone: "051-2109000",
    available: false,
    nextSlot: "Sat 11:00 AM",
    timings: "Tue, Thu, Sat: 11:00 AM – 3:00 PM",
    about: "Joint replacement specialist with expertise in knee, hip surgery and sports injuries.",
    tags: ["Joint Replacement", "Sports Injury", "Spine", "Fractures"],
    gender: "Male",
    photo: "https://ui-avatars.com/api/?name=Hassan+Qureshi&background=dc2626&color=fff&size=128"
  },
  {
    id: 5,
    name: "Dr. Nadia Farooq",
    specialty: "Pediatrician",
    qualification: "MBBS, FCPS (Pediatrics)",
    experience: 11,
    fee: 1800,
    rating: 4.8,
    reviews: 534,
    area: "F-6 Supermarket",
    clinic: "Children's Hospital Clinic",
    address: "F-6 Supermarket, Islamabad",
    phone: "051-2279001",
    available: true,
    nextSlot: "Today 5:00 PM",
    timings: "Mon–Sat: 5:00 PM – 9:00 PM",
    about: "Dedicated pediatrician specializing in newborn care, childhood vaccinations, and growth disorders.",
    tags: ["Child Health", "Vaccination", "Newborn Care", "Growth Issues"],
    gender: "Female",
    photo: "https://ui-avatars.com/api/?name=Nadia+Farooq&background=d97706&color=fff&size=128"
  },
  {
    id: 6,
    name: "Dr. Usman Khalid",
    specialty: "Neurologist",
    qualification: "MBBS, FCPS (Neurology)",
    experience: 13,
    fee: 3000,
    rating: 4.6,
    reviews: 167,
    area: "G-9 Markaz",
    clinic: "Neuro Care Center",
    address: "G-9 Markaz, Islamabad",
    phone: "051-2258001",
    available: true,
    nextSlot: "Tomorrow 2:00 PM",
    timings: "Mon, Wed, Fri: 2:00 PM – 6:00 PM",
    about: "Neurologist with expertise in epilepsy, migraine, stroke management, and neurodegenerative disorders.",
    tags: ["Epilepsy", "Migraine", "Stroke", "Parkinson's"],
    gender: "Male",
    photo: "https://ui-avatars.com/api/?name=Usman+Khalid&background=059669&color=fff&size=128"
  },
  {
    id: 7,
    name: "Dr. Rabia Saeed",
    specialty: "ENT Specialist",
    qualification: "MBBS, FCPS (ENT)",
    experience: 8,
    fee: 1500,
    rating: 4.7,
    reviews: 289,
    area: "I-8 Markaz",
    clinic: "ENT & Allergy Clinic",
    address: "I-8 Markaz, Islamabad",
    phone: "051-4102001",
    available: true,
    nextSlot: "Today 7:00 PM",
    timings: "Mon–Sat: 5:00 PM – 9:00 PM",
    about: "Specialist in ear, nose and throat disorders including sinusitis, hearing loss, and tonsillitis.",
    tags: ["Sinusitis", "Hearing Loss", "Tonsillitis", "Allergy"],
    gender: "Female",
    photo: "https://ui-avatars.com/api/?name=Rabia+Saeed&background=be185d&color=fff&size=128"
  },
  {
    id: 8,
    name: "Dr. Faisal Imran",
    specialty: "Gastroenterologist",
    qualification: "MBBS, FCPS (Gastroenterology)",
    experience: 16,
    fee: 3500,
    rating: 4.8,
    reviews: 203,
    area: "F-10 Markaz",
    clinic: "Islamabad Diagnostic Centre",
    address: "IDC, F-10 Markaz, Islamabad",
    phone: "051-2100001",
    available: false,
    nextSlot: "Mon 10:00 AM",
    timings: "Mon, Wed, Fri: 10:00 AM – 1:00 PM",
    about: "Expert in endoscopy, colonoscopy, liver diseases, and inflammatory bowel disease.",
    tags: ["Endoscopy", "Liver Disease", "IBD", "Acid Reflux"],
    gender: "Male",
    photo: "https://ui-avatars.com/api/?name=Faisal+Imran&background=1d4ed8&color=fff&size=128"
  },
  {
    id: 9,
    name: "Dr. Amna Baig",
    specialty: "Psychiatrist",
    qualification: "MBBS, FCPS (Psychiatry)",
    experience: 10,
    fee: 2500,
    rating: 4.9,
    reviews: 145,
    area: "E-7",
    clinic: "Mind & Wellness Clinic",
    address: "E-7, Islamabad",
    phone: "051-2650001",
    available: true,
    nextSlot: "Tomorrow 3:00 PM",
    timings: "Tue, Thu, Sat: 3:00 PM – 7:00 PM",
    about: "Psychiatrist specializing in depression, anxiety, OCD, bipolar disorder, and addiction treatment.",
    tags: ["Depression", "Anxiety", "OCD", "Bipolar Disorder"],
    gender: "Female",
    photo: "https://ui-avatars.com/api/?name=Amna+Baig&background=9333ea&color=fff&size=128"
  },
  {
    id: 10,
    name: "Dr. Kamran Ashraf",
    specialty: "Urologist",
    qualification: "MBBS, FCPS (Urology)",
    experience: 19,
    fee: 3000,
    rating: 4.7,
    reviews: 178,
    area: "Bahria Town",
    clinic: "Bahria International Hospital",
    address: "Bahria Town Phase 8, Rawalpindi",
    phone: "051-5700001",
    available: true,
    nextSlot: "Today 3:00 PM",
    timings: "Mon–Sat: 3:00 PM – 7:00 PM",
    about: "Urologist experienced in kidney stones, prostate issues, urinary tract infections, and laparoscopic surgery.",
    tags: ["Kidney Stones", "Prostate", "UTI", "Laparoscopy"],
    gender: "Male",
    photo: "https://ui-avatars.com/api/?name=Kamran+Ashraf&background=b45309&color=fff&size=128"
  },
  {
    id: 11,
    name: "Dr. Zara Ahmed",
    specialty: "Ophthalmologist",
    qualification: "MBBS, FCPS (Ophthalmology)",
    experience: 12,
    fee: 2000,
    rating: 4.8,
    reviews: 267,
    area: "G-11 Markaz",
    clinic: "Eye Care Vision Center",
    address: "G-11 Markaz, Islamabad",
    phone: "051-2290001",
    available: true,
    nextSlot: "Today 6:30 PM",
    timings: "Mon–Sat: 10:00 AM – 2:00 PM, 5:00 PM – 8:00 PM",
    about: "Eye specialist with expertise in cataract surgery, LASIK, glaucoma, and diabetic retinopathy.",
    tags: ["Cataract", "LASIK", "Glaucoma", "Diabetic Eye"],
    gender: "Female",
    photo: "https://ui-avatars.com/api/?name=Zara+Ahmed&background=0891b2&color=fff&size=128"
  },
  {
    id: 12,
    name: "Dr. Shahid Iqbal",
    specialty: "General Physician",
    qualification: "MBBS, MCPS (Family Medicine)",
    experience: 7,
    fee: 1000,
    rating: 4.6,
    reviews: 412,
    area: "I-10 Markaz",
    clinic: "City Health Clinic",
    address: "I-10 Markaz, Islamabad",
    phone: "051-4480001",
    available: true,
    nextSlot: "Today 8:00 PM",
    timings: "Mon–Sun: 9:00 AM – 10:00 PM",
    about: "General physician providing primary care, managing chronic diseases, and routine health checkups.",
    tags: ["Fever", "Diabetes", "Hypertension", "Checkup"],
    gender: "Male",
    photo: "https://ui-avatars.com/api/?name=Shahid+Iqbal&background=16a34a&color=fff&size=128"
  },
  {
    id: 13,
    name: "Dr. Hina Nawaz",
    specialty: "Endocrinologist",
    qualification: "MBBS, FCPS (Endocrinology)",
    experience: 15,
    fee: 3000,
    rating: 4.9,
    reviews: 189,
    area: "F-7 Markaz",
    clinic: "Diabetes & Hormone Clinic",
    address: "F-7 Markaz, Islamabad",
    phone: "051-2272001",
    available: false,
    nextSlot: "Wed 11:00 AM",
    timings: "Mon, Wed, Fri: 11:00 AM – 3:00 PM",
    about: "Expert in diabetes management, thyroid disorders, PCOS, and hormonal imbalances.",
    tags: ["Diabetes", "Thyroid", "PCOS", "Hormonal Issues"],
    gender: "Female",
    photo: "https://ui-avatars.com/api/?name=Hina+Nawaz&background=e11d48&color=fff&size=128"
  },
  {
    id: 14,
    name: "Dr. Ali Raza",
    specialty: "Pulmonologist",
    qualification: "MBBS, FCPS (Pulmonology)",
    experience: 11,
    fee: 2500,
    rating: 4.7,
    reviews: 134,
    area: "PWD Society",
    clinic: "Lung & Chest Clinic",
    address: "PWD Society, Islamabad",
    phone: "051-2875001",
    available: true,
    nextSlot: "Tomorrow 12:00 PM",
    timings: "Mon–Sat: 11:00 AM – 3:00 PM",
    about: "Pulmonologist specializing in asthma, COPD, tuberculosis, and sleep apnea.",
    tags: ["Asthma", "COPD", "TB", "Sleep Apnea"],
    gender: "Male",
    photo: "https://ui-avatars.com/api/?name=Ali+Raza&background=0369a1&color=fff&size=128"
  },
  {
    id: 15,
    name: "Dr. Fareeha Mirza",
    specialty: "Dentist",
    qualification: "BDS, FCPS (Oral Surgery)",
    experience: 6,
    fee: 1200,
    rating: 4.8,
    reviews: 321,
    area: "G-6 Supermarket",
    clinic: "Smile Dental Studio",
    address: "G-6 Supermarket, Islamabad",
    phone: "051-2829001",
    available: true,
    nextSlot: "Today 5:30 PM",
    timings: "Mon–Sat: 11:00 AM – 8:00 PM",
    about: "Cosmetic and restorative dentist specializing in teeth whitening, implants, braces, and root canals.",
    tags: ["Braces", "Teeth Whitening", "Implants", "Root Canal"],
    gender: "Female",
    photo: "https://ui-avatars.com/api/?name=Fareeha+Mirza&background=0d9488&color=fff&size=128"
  },
  {
    id: 16,
    name: "Dr. Bilal Sheikh",
    specialty: "Nephrologist",
    qualification: "MBBS, FCPS (Nephrology)",
    experience: 18,
    fee: 3500,
    rating: 4.8,
    reviews: 112,
    area: "H-8 Markaz",
    clinic: "Kidney Care Center",
    address: "H-8 Markaz, Islamabad",
    phone: "051-4856001",
    available: true,
    nextSlot: "Tomorrow 9:00 AM",
    timings: "Mon–Fri: 9:00 AM – 1:00 PM",
    about: "Nephrologist with expertise in chronic kidney disease, dialysis, kidney transplant care, and hypertension.",
    tags: ["Kidney Disease", "Dialysis", "Transplant", "Hypertension"],
    gender: "Male",
    photo: "https://ui-avatars.com/api/?name=Bilal+Sheikh&background=7c2d12&color=fff&size=128"
  }
];

const specialties = [
  { name: "General Physician", icon: "🩺", count: 45 },
  { name: "Gynecologist", icon: "👩‍⚕️", count: 38 },
  { name: "Dermatologist", icon: "🔬", count: 29 },
  { name: "Cardiologist", icon: "❤️", count: 24 },
  { name: "Pediatrician", icon: "👶", count: 41 },
  { name: "Orthopedic Surgeon", icon: "🦴", count: 22 },
  { name: "Neurologist", icon: "🧠", count: 18 },
  { name: "ENT Specialist", icon: "👂", count: 27 },
  { name: "Psychiatrist", icon: "🧘", count: 16 },
  { name: "Ophthalmologist", icon: "👁️", count: 21 },
  { name: "Dentist", icon: "🦷", count: 53 },
  { name: "Urologist", icon: "⚕️", count: 15 }
];

const areas = [
  "All Areas", "F-6 Supermarket", "F-7 Markaz", "F-8 Markaz", "F-10 Markaz",
  "G-6 Supermarket", "G-9 Markaz", "G-10 Markaz", "G-11 Markaz",
  "I-8 Markaz", "I-10 Markaz", "H-8 Markaz", "E-7",
  "Blue Area", "DHA Phase 2", "Bahria Town", "PWD Society"
];
